'use client';
import { useAnimeData } from '@/hooks/useAnimeData';
import { AnimeCard } from '@/components/AnimeCard';
import { motion } from 'framer-motion';
import Link from 'next/link';
import { useRef, useState, useEffect, useMemo } from 'react';
import { compareSeasons, getBaseTitle } from '@/utils/animeUtils';
import { Anime } from '@/types/anime';
import { ChevronLeft, ChevronRight, ArrowUpRight, Play } from 'lucide-react';
function getCurrentSeason() { const now = new Date(); const season = now.getMonth() < 3 ? '冬' : now.getMonth() < 6 ? '春' : now.getMonth() < 9 ? '夏' : '秋'; return `${now.getFullYear()} ${season}`; }
export default function HomePage() {
 const { animeList, loading } = useAnimeData(); const currentSeasonLabel = useMemo(() => getCurrentSeason(), []); const recommended = useMemo(() => { const grouped = animeList.reduce((acc, anime) => { const base = getBaseTitle(anime); (acc[base] ||= []).push(anime); return acc; }, {} as Record<string, Anime[]>); return Object.values(grouped).map(group => group.sort((a,b) => compareSeasons(a.season, b.season))[0]).slice(0,15); }, [animeList]);
 if (loading) return <div className="m3-page" style={{ textAlign: 'center', color: '#49454f' }}>あなたの棚を準備しています…</div>;
 const watching = animeList.filter(a => a.userData?.status === '視聴中'); const seasonal = animeList.filter(a => a.season === currentSeasonLabel); const planToWatch = animeList.filter(a => a.userData?.status === '見たい');
 return <div className="m3-page" style={{ maxWidth: 'none', paddingLeft: 0, paddingRight: 0 }}>
   <section style={{ padding: '18px clamp(20px,4vw,64px) 40px', display: 'grid', gridTemplateColumns: 'minmax(0,1fr) auto', gap: 24, alignItems: 'end' }}>
     <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }}><div className="m3-eyebrow">ANIME VAULT · PERSONAL SPACE</div><h1 className="m3-title" style={{ fontSize: 'clamp(45px,7vw,82px)', lineHeight: .95 }}>今日の気分に、<br /><em style={{ color: '#6750a4' }}>物語を。</em></h1><p className="m3-subtitle" style={{ maxWidth: 510 }}>観たい作品、続きが気になる作品、心に残った作品。あなたのアニメ時間をひとつの場所に。</p></motion.div>
     <div className="m3-surface" style={{ minWidth: 180, padding: '18px 20px', background: '#e9ddff' }}><div style={{ color: '#49454f', fontSize: 12, fontWeight: 700 }}>COLLECTION</div><strong style={{ display: 'block', fontSize: 30, color: '#21005d', marginTop: 5 }}>{animeList.length}</strong><span style={{ color: '#49454f', fontSize: 12 }}>タイトルを保存中</span></div>
   </section>
  {watching.length > 0 && <section style={{ margin: '0 clamp(20px,4vw,64px) 42px', padding: 24, background: 'var(--secondary-container)', borderRadius: 30 }}><div style={{ display:'flex', justifyContent:'space-between', gap:16, alignItems:'center', marginBottom: 18 }}><div><div className="m3-eyebrow" style={{ color:'var(--tertiary)' }}>KEEP WATCHING</div><h2 className="m3-title" style={{ fontSize: 27, margin: '3px 0' }}>つづきを観る</h2></div><Link className="m3-button" href="/library" style={{ textDecoration:'none', whiteSpace:'nowrap' }}><Play size={15} style={{ verticalAlign:'-3px', marginRight:5 }} />ライブラリ</Link></div><div style={{ display:'flex', gap:16 }} className="home-card-strip no-scrollbar">{watching.slice(0,6).map((a,i) => <div key={a.id} style={{ width:'clamp(140px,18vw,190px)', flexShrink:0 }}><AnimeCard anime={a} showProgress index={i}/></div>)}</div></section>}
   <div style={{ display:'flex', flexDirection:'column', gap: 42 }}><CarouselSection title={`今季の注目 · ${currentSeasonLabel}`} href={`/anime?season=${encodeURIComponent(currentSeasonLabel)}`}>{seasonal.length ? seasonal.map((a,i)=><CardFrame key={a.id}><AnimeCard anime={a} index={i}/></CardFrame>) : <Empty text={`${currentSeasonLabel} の作品はまだありません`} />}</CarouselSection><CarouselSection title="観たいリスト" subtitle="次に出会う、心が動く一本。" href="/library">{planToWatch.length ? planToWatch.map((a,i)=><CardFrame key={a.id}><AnimeCard anime={a} index={i}/></CardFrame>) : <Empty text="「見たい」作品をライブラリに追加しましょう" />}</CarouselSection><CarouselSection title="あなたへのおすすめ" subtitle="コレクションから選んだ、新しい物語。" href="/anime">{recommended.length ? recommended.map((a,i)=><CardFrame key={a.id}><AnimeCard anime={a} index={i}/></CardFrame>) : <Empty text="作品がありません" />}</CarouselSection></div>
 </div>;
}
function Empty({text}:{text:string}) { return <div className="m3-surface" style={{ padding:32, color:'#49454f', width:'100%', textAlign:'center' }}>{text}</div>; }
function CarouselSection({ title, subtitle, children, href }: {title:string; subtitle?:string; children:React.ReactNode; href:string}) { const ref=useRef<HTMLDivElement>(null); const [can,setCan]=useState({left:false,right:true}); const check=()=>{ if(ref.current) { const {scrollLeft,scrollWidth,clientWidth}=ref.current; setCan({left:scrollLeft>10,right:scrollLeft<scrollWidth-clientWidth-10}); }}; useEffect(()=>{check(); window.addEventListener('resize',check); return()=>window.removeEventListener('resize',check);},[children]); const scroll=(direction:'left'|'right')=>ref.current?.scrollBy({left:(direction==='left'?-1:1)*(ref.current.clientWidth*.8),behavior:'smooth'}); return <section><div style={{ padding:'0 clamp(20px,4vw,64px)', display:'flex', justifyContent:'space-between', alignItems:'end', gap:16, marginBottom:14 }}><div><h2 className="m3-title" style={{ fontSize:'clamp(24px,3vw,32px)', margin:0 }}>{title}</h2>{subtitle&&<p className="m3-subtitle" style={{fontSize:14}}>{subtitle}</p>}</div><Link href={href} style={{ color:'#6750a4', fontWeight:800, textDecoration:'none', whiteSpace:'nowrap', fontSize:14 }}>すべて見る <ArrowUpRight size={15} style={{verticalAlign:'-3px'}}/></Link></div><div style={{position:'relative'}}>{can.left&&<button aria-label="前へ" onClick={()=>scroll('left')} className="scroll-btn-hover" style={{position:'absolute',zIndex:2,left:18,top:'42%',border:0,borderRadius:99,width:42,height:42,background:'#fffbff',color:'#6750a4',cursor:'pointer',boxShadow:'0 3px 10px #0002'}}><ChevronLeft/></button>}{can.right&&<button aria-label="次へ" onClick={()=>scroll('right')} className="scroll-btn-hover" style={{position:'absolute',zIndex:2,right:18,top:'42%',border:0,borderRadius:99,width:42,height:42,background:'#fffbff',color:'#6750a4',cursor:'pointer',boxShadow:'0 3px 10px #0002'}}><ChevronRight/></button>}<div ref={ref} onScroll={check} className="home-card-strip no-scrollbar" style={{display:'flex',gap:16}}>{children}</div></div></section>; }
function CardFrame({children}:{children:React.ReactNode}) { return <div style={{ width:'clamp(140px,17vw,210px)', flexShrink:0 }}>{children}</div>; }
